<a href="https://colab.research.google.com/github/Ekansh0801/90-DAYS-OF-MACHINE-LEARNING/blob/main/DAY_15.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Matrix Operations

In [1]:
import numpy as np

### Matrix Addition

#### Two Matrices can be added only if they had same shape

In [3]:
# creating two matrices

A = np.array([[2,3],[4,5]])

B = np.array([[6,7],[8,9]])

sum = A + B
print(sum)
print(sum.shape)

[[ 8 10]
 [12 14]]
(2, 2)


In [4]:
# two matrices with random values

matrix_1 = np.random.randint(10,size=(3,3))
matrix_2 = np.random.randint(20,size=(3,3))

sum = np.add(matrix_1,matrix_2)
print(sum)

[[26  9 14]
 [ 3 11 18]
 [11 25  5]]


In [5]:
# two matrices with random values

matrix_1 = np.random.randint(10,size=(3,3))
matrix_2 = np.random.randint(20,size=(3,4))

sum_2 = np.add(matrix_1,matrix_2)  # we will get error becuse shape is different
print(sum_2)

ValueError: operands could not be broadcast together with shapes (3,3) (3,4) 

### Matrix Subraction

In [6]:
# creating two matrices

A = np.array([[2,3],[4,5]])

B = np.array([[6,7],[8,9]])

diff = A - B
print(diff)
print(diff.shape)

[[-4 -4]
 [-4 -4]]
(2, 2)


In [8]:
# two matrices with random values

matrix_1 = np.random.randint(10,size=(3,3))
matrix_2 = np.random.randint(20,size=(3,3))

diff = np.subtract(matrix_1,matrix_2)
print(diff)

[[ -8 -15 -16]
 [-15   0  -5]
 [-18 -13   1]]


### Multiplying a Matrix By scalar

In [14]:
x = 5
y = np.random.randint(10,size=(4,4))

print(y)

[[8 3 0 5]
 [5 3 5 4]
 [6 3 6 2]
 [0 9 1 5]]


In [15]:
prod = np.multiply(x,y)
print(prod)

[[40 15  0 25]
 [25 15 25 20]
 [30 15 30 10]
 [ 0 45  5 25]]


### Multiplying two matrices

In [18]:
# two matrices with random values

matrix_1 = np.random.randint(5,size=(3,3))
matrix_2 = np.random.randint(5,size=(3,4))

In [19]:
print(matrix_1)

[[0 2 4]
 [4 4 0]
 [4 3 2]]


In [21]:
print(matrix_2)

[[1 3 3 1]
 [2 4 3 1]
 [1 4 4 2]]


In [22]:
product = np.dot(matrix_1,matrix_2)
print(product)

[[ 8 24 22 10]
 [12 28 24  8]
 [12 32 29 11]]


In [23]:
print(product.shape)

(3, 4)


In [26]:
# two matrices with random values

matrix_3 = np.random.randint(5,size=(3,3))
matrix_4 = np.random.randint(5,size=(4,4))

In [27]:
prod = matrix_3 * matrix_4
print(prod)

ValueError: operands could not be broadcast together with shapes (3,3) (4,4) 

### element wise matix multiplication

In [29]:
# two matrices with random values

matrix_3 = np.random.randint(5,size=(3,3))
matrix_4 = np.random.randint(5,size=(3,3))

result = np.multiply(matrix_3,matrix_4)
print(result)

[[ 0  0  0]
 [ 0  0  2]
 [12  0 16]]
