<a href="https://colab.research.google.com/github/Ekansh0801/90-DAYS-OF-MACHINE-LEARNING/blob/main/DAY_03.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy

In [1]:
import numpy as np

### List vs Numpy - Time taken

In [2]:
from time import process_time

### Time taken by a list

In [6]:
python_list = [i for i in  range(10000)]

start_time = process_time()

python_list = [i + 5 for i in python_list]

end_time = process_time()

print(end_time - start_time)

0.00125796200000039


### Time taken by numpy

In [7]:
np_array = np.array([i for i in range(10000)])

start_time = process_time()

np_array += 5

end_time = process_time()

print(end_time - start_time)

0.00116898100000018


# NumPy Arrays

In [10]:
list1 = [1,2,3,4,5]
print(list1)
type(list1)

[1, 2, 3, 4, 5]


list

In [11]:
np_array = np.array([1,2,3,4,5])
print(np_array)
type(np_array)

[1 2 3 4 5]


numpy.ndarray

In [12]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [13]:
a.shape

(4,)

In [14]:
b = np.array([(1,2,3,4),(5,6,7,8)])
print(b)

[[1 2 3 4]
 [5 6 7 8]]


In [15]:
b.shape

(2, 4)

In [16]:
c = np.array([(1,2,3,4),(5,6,7,8)],dtype=float)
print(c)

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


### Initial Placeholders in numpy arrays

In [19]:
# create a numoy array of zeros

x = np.zeros((4,5))
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [20]:
# create a numpy arrays of ones

y = np.ones((3,3))
print(y)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [22]:
# array of a particular value

z = np.full((5,4),5,dtype=float)
print(z)

[[5. 5. 5. 5.]
 [5. 5. 5. 5.]
 [5. 5. 5. 5.]
 [5. 5. 5. 5.]
 [5. 5. 5. 5.]]


In [23]:
# create an identity matrix

a = np.eye(5)
print(a)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [26]:
# create a numpy array with random values

b = np.random.random((3,4))
print(b)

[[0.9346138  0.02547498 0.62689062 0.66167565]
 [0.77639827 0.10724209 0.76833882 0.17721653]
 [0.76783861 0.24528215 0.37459654 0.21067114]]


In [30]:
# random values array with integers with specific range

c = np.random.randint(10,100,(3,5))
print(c)

[[38 45 43 86 27]
 [93 38 98 26 83]
 [26 52 23 79 96]]


In [32]:
# array of evenly space values --> specifying number of values also

d = np.linspace(10,30,5)
print(d)

[10. 15. 20. 25. 30.]


In [34]:
# array of evenly spaced values  --> specifiying the step

e = np.arange(10,30,5)
print(e)

[10 15 20 25]


In [36]:
# convert a lit into numpy array

list2 = [10,20,20,20,50]

np_array = np.asarray(list2)  # optimal
# np_array = np.array(list2)
print(np_array)
type(np_array)

[10 20 20 20 50]


numpy.ndarray

### Analyzing numpy array

In [37]:
c = np.random.randint(10,90,(5,5))
print(c)

[[44 63 69 28 33]
 [87 77 34 59 57]
 [85 64 49 48 14]
 [14 31 54 20 12]
 [75 20 64 28 49]]


In [39]:
print(c.shape)

(5, 5)


In [40]:
# number of dimension
print(c.ndim)

2


In [41]:
#number of elements in an array
print(c.size)

25


In [42]:
# cheking data types of values in array
print(c.dtype)

int64


# Mathematical operations on a np array

In [43]:
list1 = [1,2,3,4,5]
list2 = [6,7,8,9,10]

print(list1 + list2)   # concatenate two lists

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [47]:
a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))

print(a)
print(b)
print(a + b)
print(b - a)
print(a * b)
print(a / b)

[[2 9 2]
 [0 5 0]
 [3 7 8]]
[[10 18 12]
 [16 17 14]
 [17 17 13]]
[[12 27 14]
 [16 22 14]
 [20 24 21]]
[[ 8  9 10]
 [16 12 14]
 [14 10  5]]
[[ 20 162  24]
 [  0  85   0]
 [ 51 119 104]]
[[0.2        0.5        0.16666667]
 [0.         0.29411765 0.        ]
 [0.17647059 0.41176471 0.61538462]]


In [49]:
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))

[[12 27 14]
 [16 22 14]
 [20 24 21]]
[[ -8  -9 -10]
 [-16 -12 -14]
 [-14 -10  -5]]
[[ 20 162  24]
 [  0  85   0]
 [ 51 119 104]]
[[0.2        0.5        0.16666667]
 [0.         0.29411765 0.        ]
 [0.17647059 0.41176471 0.61538462]]


### Array manipulation

In [50]:
array = np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

[[6 3 4]
 [6 2 7]]
(2, 3)


In [52]:
# transpose
trans = np.transpose(array)
print(trans)
print(trans.shape)

[[6 6]
 [3 2]
 [4 7]]
(3, 2)


In [54]:
trans2 = array.T
print(trans2.shape)

(3, 2)


In [56]:
# reshaping an array
a = np.random.randint(0,10,(2,3))
print(a)
print(a.shape)

[[7 9 0]
 [7 3 7]]
(2, 3)


In [58]:
b = a.reshape(3,2)
print(b)

[[7 9]
 [0 7]
 [3 7]]
